name: Deploy Frontend

on:
  push:
    branches:
      - main  # Executa o CI/CD ao fazer push na branch main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 🛠 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: yarn install --frozen-lockfile

      - name: 🔨 Construir aplicação
        run: yarn build

      - name: 📦 Criar imagem Docker
        run: docker build -t seu-usuario/seu-repositorio:latest .

      - name: 🔐 Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🚀 Publicar imagem no Docker Hub
        run: docker push seu-usuario/seu-repositorio:latest

      - name: 🔄 Deploy no servidor via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull seu-usuario/seu-repositorio:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 80:80 seu-usuario/seu-repositorio:latest
